export const routes = {
  signIn: "/sign-in",
  signUp: "/sign-up",
  mainPage: "/",
  welcomePage: "/",
  roomListPage: "/rooms",

  accountPage: "/account",
  fileTalkMainPage: "/fileTalk",
  orderSubscriptionPage: "/order-subscription",
  invoicePage: "/invoice-list",
  uploadScreenPage: "/fileTalk/start",
  uploadDetails: "/fileTalk/upload-details",
  fileView: "/fileTalk/file-view`",
  searchResultsPage: "/fileTalk/search`",
  settingsPage: "/",
  profilePage: "/profile",
  storagePage: "/storage",
  subscriptionPage: "/subscription",
  billingPage: "/billing",
};
